const KEY="rodies_v2_products", CART="rodies_v2_cart", ADMIN="rodies_v2_admin";
const ADMIN_PASSWORD="1a2b3c4d5", MAX_COLOURS=10, MAX_PHOTOS_PER_COLOUR=6;
const starter=[
{id:1,name:"Rodies Runner",price:899,colors:["Black","White"],sizes:["6","7","8","9"],photos:[{color:"Black",image:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80"},{color:"White",image:"https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?auto=format&fit=crop&w=900&q=80"}]},
{id:2,name:"Street Classic",price:1499,colors:["Black","Blue"],sizes:["7","8","9","10"],photos:[{color:"Black",image:"https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80"},{color:"Blue",image:"https://images.unsplash.com/photo-1554130841-5a3d3a7a3e9d?auto=format&fit=crop&w=900&q=80"}]},
{id:3,name:"Everyday Flex",price:1999,colors:["Grey","White"],sizes:["6","7","8","9","10"],photos:[{color:"Grey",image:"https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=80"},{color:"White",image:"https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?auto=format&fit=crop&w=900&q=80"}]}];
function normalizeProducts(list){return(list||[]).map(p=>{let photos=Array.isArray(p.photos)?p.photos.slice():[];if(!photos.length&&p.image)photos=[{color:(p.colors&&p.colors[0])||"Default",image:p.image}];photos=photos.filter(x=>x&&x.image).map(x=>({color:String(x.color||"Default"),image:x.image}));return{...p,photos,colors:[...new Set(photos.map(x=>x.color))].slice(0,MAX_COLOURS)}})}
if(!localStorage.getItem(KEY))localStorage.setItem(KEY,JSON.stringify(starter));else localStorage.setItem(KEY,JSON.stringify(normalizeProducts(JSON.parse(localStorage.getItem(KEY)||"[]"))));
const getP=()=>normalizeProducts(JSON.parse(localStorage.getItem(KEY)||"[]")),getCart=()=>JSON.parse(localStorage.getItem(CART)||"[]"),money=n=>"₹"+Number(n).toLocaleString("en-IN"),firstImage=p=>p.photos?.[0]?.image||p.image||"https://via.placeholder.com/900x700?text=Rodies";
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function render(){const el=document.getElementById("products");if(!el)return;let a=getP(),q=(document.getElementById("search")?.value||"").toLowerCase(),b=document.getElementById("budget")?.value,s=document.getElementById("sort")?.value;a=a.filter(p=>p.name.toLowerCase().includes(q)||(p.colors||[]).join(" ").toLowerCase().includes(q));if(b)a=a.filter(p=>p.price<+b);if(s==="asc")a.sort((x,y)=>x.price-y.price);if(s==="desc")a.sort((x,y)=>y.price-x.price);el.innerHTML=a.map(p=>`<article class="card"><a href="product.html?id=${p.id}"><img src="${firstImage(p)}" alt="${escapeHtml(p.name)}"></a><div class="card-body"><h3>${escapeHtml(p.name)}</h3><div class="price">${money(p.price)}</div><p class="muted">Colours: ${(p.colors||[]).map(escapeHtml).join(", ")}<br>Sizes: ${(p.sizes||[]).map(escapeHtml).join(", ")}</p><button class="btn" onclick="addCart(${p.id})">Add to cart</button></div></article>`).join("")||"<p>No shoes found.</p>";renderCart();updateCount()}
function addCart(id){let c=getCart(),p=getP().find(x=>x.id===id);if(!p)return;c.push({id:p.id,name:p.name,price:p.price});localStorage.setItem(CART,JSON.stringify(c));renderCart();updateCount()}
function removeCart(i){let c=getCart();c.splice(i,1);localStorage.setItem(CART,JSON.stringify(c));renderCart();updateCount()}
function renderCart(){const el=document.getElementById("cartItems");if(!el)return;let c=getCart();el.innerHTML=c.length?c.map((x,i)=>`<div class="cart-row"><span>${escapeHtml(x.name)}</span><b>${money(x.price)} <button class="btn secondary" onclick="removeCart(${i})">Remove</button></b></div>`).join(""):"<p class='muted'>Your cart is empty.</p>";let t=c.reduce((s,x)=>s+x.price,0),total=document.getElementById("cartTotal");if(total)total.innerHTML=`<h3>Total: ${money(t)}</h3>`}
function updateCount(){const e=document.getElementById("cartCount");if(e)e.textContent=getCart().length}
function checkout(){let c=getCart();if(!c.length)return alert("Add a shoe first.");let text="Hello Rodies! I would like to order:%0A"+c.map(x=>`• ${x.name} - ${money(x.price)}`).join("%0A")+`%0A%0ATotal: ${money(c.reduce((s,x)=>s+x.price,0))}`;window.open("https://wa.me/?text="+text,"_blank")}
function colourGroups(p){const map={};(p.photos||[]).forEach(x=>{if(!map[x.color])map[x.color]=[];if(map[x.color].length<MAX_PHOTOS_PER_COLOUR)map[x.color].push(x.image)});return Object.entries(map).map(([color,images])=>({color,images}))}
function renderProduct(){const e=document.getElementById("product");if(!e)return;let id=Number(new URLSearchParams(location.search).get("id")),p=getP().find(x=>x.id===id);if(!p){e.innerHTML="<h2>Product not found</h2>";return}const groups=colourGroups(p),g=groups[0]||{color:"Default",images:[firstImage(p)]};e.innerHTML=`<div class="product-detail"><div class="product-gallery"><img id="mainProductImage" class="main-product-image" src="${g.images[0]}" alt="${escapeHtml(p.name)}"><div id="productPhotoStrip" class="colour-thumbs"></div></div><div><p class="eyebrow">RODIES</p><h1>${escapeHtml(p.name)}</h1><div class="price">${money(p.price)}</div><h3>Colours</h3><div class="colour-buttons">${groups.map((x,i)=>`<button class="colour-btn ${i===0?'active':''}" onclick="selectColour(${i})">${escapeHtml(x.color)}</button>`).join("")}</div><p id="selectedColour" class="muted">Selected colour: ${escapeHtml(g.color)}</p><h3>Sizes</h3>${(p.sizes||[]).map(x=>`<span class="option">${escapeHtml(x)}</span>`).join("")}<br><button class="btn" onclick="addCart(${p.id})">Add to cart</button></div></div>`;window.currentColourGroups=groups;selectColour(0);updateCount()}
function selectColour(i){const groups=window.currentColourGroups||[],g=groups[i];if(!g)return;const img=document.getElementById("mainProductImage");if(img){img.src=g.images[0];img.alt=g.color}document.querySelectorAll(".colour-btn").forEach((b,n)=>b.classList.toggle("active",n===i));const s=document.getElementById("selectedColour");if(s)s.textContent="Selected colour: "+g.color;const strip=document.getElementById("productPhotoStrip");if(strip)strip.innerHTML=g.images.map((src,n)=>`<button class="colour-choice ${n===0?'active':''}" onclick="selectPhoto(${n})"><img src="${src}" alt="${escapeHtml(g.color)} photo ${n+1}"><span>Photo ${n+1}</span></button>`).join("");window.currentSelectedImages=g.images}
function selectPhoto(i){const imgs=window.currentSelectedImages||[];if(imgs[i]){const img=document.getElementById("mainProductImage");if(img)img.src=imgs[i];document.querySelectorAll(".colour-choice").forEach((b,n)=>b.classList.toggle("active",n===i))}}
function loginAdmin(){if(document.getElementById("adminPassword").value===ADMIN_PASSWORD){sessionStorage.setItem(ADMIN,"1");showAdmin()}else document.getElementById("loginMsg").textContent="Incorrect password."}
function initAdmin(){if(sessionStorage.getItem(ADMIN)==="1")showAdmin()}
function showAdmin(){const l=document.getElementById("adminLogin"),d=document.getElementById("dashboard");if(l)l.hidden=true;if(d)d.hidden=false;setupColourGroups();renderAdmin()}
function logoutAdmin(){sessionStorage.removeItem(ADMIN);location.reload()}
function setupColourGroups(){const b=document.getElementById("colourGroups");if(b&&!b.children.length)addColourGroup();updateColourCounter()}
function addColourGroup(){const b=document.getElementById("colourGroups");if(!b)return;if(b.children.length>=MAX_COLOURS)return alert("You can add a maximum of 10 colours per shoe.");const row=document.createElement("div");row.className="colour-group";row.innerHTML=`<div class="colour-group-head"><strong>Colour ${b.children.length+1}</strong><input class="colour-name" placeholder="Colour name (e.g. Black)"><button type="button" class="remove-colour" onclick="removeColourGroup(this)">Remove colour</button></div><div class="group-photos"></div><button type="button" class="btn secondary add-photo" onclick="addColourPhoto(this)">+ Add photo</button> <span class="photo-count muted">0 / 6 photos</span>`;b.appendChild(row);addColourPhoto(row.querySelector(".add-photo"));updateColourCounter()}
function removeColourGroup(x){x.closest(".colour-group").remove();renumberColourGroups();updateColourCounter()}
function renumberColourGroups(){document.querySelectorAll(".colour-group").forEach((g,i)=>g.querySelector("strong").textContent="Colour "+(i+1))}
function addColourPhoto(x){const g=x.closest(".colour-group"),p=g.querySelector(".group-photos");if(p.children.length>=MAX_PHOTOS_PER_COLOUR)return alert("A single colour can have a maximum of 6 photos.");const r=document.createElement("div");r.className="group-photo";r.innerHTML=`<input class="colour-file" type="file" accept="image/*" onchange="updateColourCounter()"><button type="button" class="remove-photo" onclick="removeColourPhoto(this)">Remove</button>`;p.appendChild(r);updateColourCounter()}
function removeColourPhoto(x){x.closest(".group-photo").remove();updateColourCounter()}
function updateColourCounter(){const gs=[...document.querySelectorAll(".colour-group")],m=document.getElementById("colourLimitMsg");if(m)m.textContent=`${gs.length} / ${MAX_COLOURS} colours added`;gs.forEach(g=>{const n=[...g.querySelectorAll(".colour-file")].filter(x=>x.files.length).length,c=g.querySelector(".photo-count");if(c)c.textContent=`${n} / ${MAX_PHOTOS_PER_COLOUR} photos selected`})}
async function addProduct(){if(sessionStorage.getItem(ADMIN)!=="1")return;const name=document.getElementById("pName").value.trim(),price=+document.getElementById("pPrice").value,sizes=document.getElementById("pSizes").value.split(",").map(x=>x.trim()).filter(Boolean);if(!name||!price)return alert("Enter name and price.");const gs=[...document.querySelectorAll(".colour-group")];if(!gs.length)return alert("Add at least one colour.");if(gs.length>MAX_COLOURS)return alert("Maximum 10 colours allowed.");const photos=[];for(const g of gs){const color=g.querySelector(".colour-name").value.trim(),files=[...g.querySelectorAll(".colour-file")].filter(x=>x.files.length).map(x=>x.files[0]);if(!color)return alert("Enter a colour name for every colour.");if(!files.length)return alert(`Please upload at least 1 photo for ${color}.`);for(const f of files)photos.push({color,image:await fileToDataURL(f)})}let a=getP();a.unshift({id:Date.now(),name,price,colors:[...new Set(photos.map(x=>x.color))],sizes,photos,image:photos[0].image});try{localStorage.setItem(KEY,JSON.stringify(a))}catch(e){return alert("The photos are too large for browser storage. Please use smaller images.")}clearProductForm();renderAdmin()}
function fileToDataURL(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
function clearProductForm(){document.getElementById("pName").value="";document.getElementById("pPrice").value="";document.getElementById("pSizes").value="";document.getElementById("colourGroups").innerHTML="";addColourGroup()}
function renderAdmin(){const e=document.getElementById("adminProducts");if(!e)return;e.innerHTML=getP().map(p=>`<article class="card"><img src="${firstImage(p)}"><div class="card-body"><h3>${escapeHtml(p.name)}</h3><div class="price">${money(p.price)}</div><p class="muted">${(p.colors||[]).map(escapeHtml).join(", ")} · ${(p.photos||[]).length} total photo(s)</p><button class="btn delete" onclick="deleteProduct(${p.id})">Delete</button></div></article>`).join("")}
function deleteProduct(id){if(confirm("Delete this product?")){localStorage.setItem(KEY,JSON.stringify(getP().filter(p=>p.id!==id)));renderAdmin()}}
function openAdminAccess(){const b=document.getElementById("adminAccess");if(b){b.hidden=false;setTimeout(()=>document.getElementById("quickAdminPassword")?.focus(),50)}}
function closeAdminAccess(){const b=document.getElementById("adminAccess");if(b)b.hidden=true}
function quickAdminLogin(){const i=document.getElementById("quickAdminPassword"),m=document.getElementById("quickLoginMsg");if(i?.value===ADMIN_PASSWORD){sessionStorage.setItem(ADMIN,"1");location.href="admin.html"}else if(m)m.textContent="Incorrect password."}
render();
