-- Rodies V2 production database starter schema.
-- Run this in a Supabase SQL editor after creating your project.
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  price integer not null check (price >= 0),
  colors text[] default '{}',
  sizes text[] default '{}',
  image_url text,
  created_at timestamptz default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_name text,
  phone text,
  items jsonb not null,
  total integer not null default 0,
  status text not null default 'new',
  created_at timestamptz default now()
);

-- For production, add Row Level Security policies so only authenticated
-- admin users can insert/update/delete products and only appropriate users
-- can access order/customer data.
